import type { Finding, Rule, ScanContext } from "../../../core/types.js";
import { finding } from "../../../core/plugin.js";
import { loadEnvFiles, parseEnvText } from "../../../core/env-file.js";
import { classifySecretValue } from "../../../core/secrets.js";
import { applyFix } from "../../../core/fixer.js";

const EXAMPLE_FILE = ".env.example";

/**
 * Keys that exist in a real env file but not in the committed template. This is
 * the check that stops a new teammate from booting a half configured app.
 *
 * The fixer only ever writes .env.example, and only ever writes the key name
 * with an empty placeholder. It never copies a value and never invents one.
 */
export const envFileDrift: Rule = {
  code: "ENV_FILE_DRIFT",
  title: "Environment files are in sync",
  async run(ctx: ScanContext): Promise<Finding[]> {
    const files = await loadEnvFiles(ctx);
    const realFiles = files.filter((f) => !f.file.includes("example") && !f.file.includes("sample"));
    if (realFiles.length === 0) return [];

    const exampleText = await ctx.files.read(EXAMPLE_FILE);
    const exampleEntries = exampleText === null ? new Map() : parseEnvText(exampleText);

    const missing: string[] = [];
    const findings: Finding[] = [];

    for (const file of realFiles) {
      for (const entry of file.entries.values()) {
        if (exampleEntries.has(entry.key) || missing.includes(entry.key)) continue;
        missing.push(entry.key);
        // One finding per drifted key, so a CI diff shows exactly what changed.
        if (exampleText !== null) {
          findings.push(
            finding.warn({
              code: "ENV_FILE_DRIFT",
              message: `${entry.key} is set in ${file.file} but missing from ${EXAMPLE_FILE}`,
              file: file.file,
              line: entry.line,
              fixable: true,
              suggestion: `Add ${entry.key}= to ${EXAMPLE_FILE} so new contributors know it is needed. Run next-doc --fix to do it.`,
            }),
          );
        }
      }
    }

    // A missing template is one problem, not one problem per variable.
    if (exampleText === null && missing.length > 0) {
      findings.push(
        finding.warn({
          code: "ENV_EXAMPLE_MISSING",
          message: `${EXAMPLE_FILE} does not exist, so ${missing.length} variable${missing.length === 1 ? "" : "s"} are undocumented`,
          file: realFiles[0]!.file,
          fixable: true,
          suggestion: `Create ${EXAMPLE_FILE} listing every key with empty values, so a new contributor knows what to set. Run next-doc --fix to generate it.`,
        }),
      );
    }

    if (missing.length === 0) {
      return [finding.pass({ code: "ENV_FILE_DRIFT", message: `${EXAMPLE_FILE} is in sync with your environment files` })];
    }

    if (ctx.fix) {
      const header =
        exampleText === null
          ? "# Environment template. Copy to .env.local and fill in real values.\n# Generated by next-doc --fix.\n"
          : exampleText.endsWith("\n") || exampleText === ""
            ? exampleText
            : `${exampleText}\n`;
      const block = [
        exampleText === null ? "" : "\n# Added by next-doc --fix. Fill in the real values locally.",
        ...missing.map((key) => `${key}=`),
        "",
      ].join("\n");

      await applyFix(ctx, {
        file: EXAMPLE_FILE,
        code: "ENV_FILE_DRIFT",
        description: `added ${missing.length} placeholder key${missing.length === 1 ? "" : "s"}`,
        contents: `${header}${block}`,
      });

      return [
        finding.pass({
          code: "ENV_FILE_DRIFT",
          message: `Added ${missing.length} missing key${missing.length === 1 ? "" : "s"} to ${EXAMPLE_FILE}`,
        }),
      ];
    }

    return findings;
  },
};

/** A committed template with a real credential in it is a leak, not a template. */
export const secretInExample: Rule = {
  code: "ENV_SECRET_IN_EXAMPLE",
  title: "No real credentials in committed templates",
  async run(ctx: ScanContext): Promise<Finding[]> {
    const text = await ctx.files.read(EXAMPLE_FILE);
    if (text === null) return [];

    const entries = parseEnvText(text);
    const findings: Finding[] = [];

    for (const entry of entries.values()) {
      const label = classifySecretValue(entry.value);
      if (!label) continue;
      findings.push(
        finding.error({
          code: "ENV_SECRET_IN_EXAMPLE",
          message: `${entry.key} in ${EXAMPLE_FILE} contains what looks like a real ${label}`,
          file: EXAMPLE_FILE,
          line: entry.line,
          fixable: false,
          suggestion: `Replace the value with an empty placeholder, then rotate the credential. ${EXAMPLE_FILE} is committed to git.`,
        }),
      );
    }

    return findings;
  },
};
